version: 1
formatters:
  standard:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/bci_compression.log
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [file, console]


formatters:
  standard:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/bci_compression.log
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [file, console]


formatters:
  standard:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/bci_compression.log
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [file, console]


formatters:
  standard:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/bci_compression.log
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [file, console]


formatters:
  standard:
    format: '%(asctime)s %(levelname)s %(name)s: %(message)s'
handlers:
  file:
    class: logging.FileHandler
    level: INFO
    formatter: standard
    filename: logs/bci_compression.log
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [file, console]

