version: "3.9"

services:
  api:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    image: ${IMAGE_NAME:-bci-compression-backend:local}
    container_name: ${SERVICE_NAME:-api}
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=8000
    env_file:
      - ${ENV_FILE:-.env}
    ports:
      - "${PORTS:-8000:8000}"
    volumes:
      - ../../:/app:rw
    working_dir: /app
    command:
      [
        "uvicorn",
        "scripts.telemetry_server:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  gui:
    build:
      context: ../../dashboard
      dockerfile: Dockerfile
      target: dev
    image: ${GUI_IMAGE_NAME:-bci-compression-gui:local}
    container_name: ${GUI_SERVICE_NAME:-gui}
    environment:
      - VITE_BACKEND_URL=${API_URL_INTERNAL:-http://api:8000}
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    ports:
      - "${GUI_PORT:-3000}:5173"
    volumes:
      - ../../dashboard:/app:rw
    depends_on:
      - api

networks:
  default:
    name: bci-compression-net
